export const ResponseMessages = {
  
  SUCCESS: 'Operation completed successfully',
  CREATED: 'Resource created successfully',
  UPDATED: 'Resource updated successfully',
  DELETED: 'Resource deleted successfully',
  FETCH_SUCCESS: 'Data fetched successfully',
  NO_CONTENT: 'No content available',
  LOGGED_IN: 'Logged in successfully',
  LOGGED_OUT: 'Logged out successfully',
  UNAUTHORIZED: 'Authentication required',
  FORBIDDEN: 'Access denied',
  USER_EXISTS: 'An account with this email already exists',
  USER_NOT_FOUND: 'User not found',
  USER_BLOCKED: 'Your account has been blocked. Please contact support',
  USER_DELETED: 'User does not exist',
  BAD_REQUEST: 'Invalid request data',
  INVALID_INPUT: 'Invalid input provided',
  CONFLICT: 'Resource conflict occurred',
  INTERNAL_SERVER_ERROR: 'An unexpected error occurred. Please try again later',
  TOKEN_EXPIRED: 'Session expired. Please log in again',
  INVALID_TOKEN: 'Invalid or malformed token',
  INVALID_FILE_TYPE: 'Only image files (jpeg, jpg, png) are allowed',
  FILE_UPLOAD_ERROR: 'Failed to upload file',
  OTP_SENT: 'OTP has been sent to your email',
  OTP_VERIFIED: 'OTP verified successfully',
  OTP_INVALID: 'Invalid OTP',
  PASSWORD_RESET: 'Password reset successfully',
  PASSWORD_FAILED: 'Invalid email or password',
  PROJECT_UPDATED: 'Project updated successfully',
  NEW_PROJECT_ADDED: 'New project created successfully',
  CREATION_FAILED: 'Failed to create resource',
  TASK_NOT_FOUND: 'Task not found',
  WORKSPACE_NOT_FOUND: 'Workspace not found',
  EMAIL_NOT_FOUND: 'No account found with this email',
  INVALID_CREDENTIALS: 'Invalid email or password',
  INVITATION_SENT: 'Invitation sent successfully',
  ATTACHMENT_REMOVED: 'Attachment removed successfully'
};