export const ResponseMessages = {
  DELETE:'Deletion completed',
  INVITAION_SEND : 'Send invitaion',
  Fetch_SUCCESS:"Data Fetched",
  SUCCESS: 'Successfully Updated',
  CREATED: 'Resource created successfully',
  NO_CONTENT: 'No content to return',
  BAD_REQUEST: 'Invalid request data',
  UNAUTHORIZED: 'Unauthorized access',
  USER_EXIST:'User is Exist',
  FORBIDDEN: 'Forbidden',
  USER_STATUS_BLOCK:"User is blocked",
 USER_STATUS_DELETE:"User is not exist",
  TOKEN_EXPIRED: 'Access token has expired',
  INVALID_TOKEN: 'Invalid token',
  NOT_FOUND: 'Resource not found',
  CONFLICT: 'Resource conflict occurred',
  INTERNAL_SERVER_ERROR: 'Something went wrong on the server',
  INVALID_FILE_TYPE: 'Only images (jpeg, jpg, png) are allowed',
  FILE_UPLOAD_ERROR: 'File upload error',
  USER_NOT_FOUND: 'User not found',
  INVALID_INPUT: 'Invalid input provided',
  OTP_SENT: 'OTP sent to your email',
  OTP_VERIFIED: 'OTP verified successfully',
  LOGGED_IN: 'Logged in successfully',
  LOGGED_OUT: 'Logged out successfully',
  PASSWORD_RESET: 'Password reset successfully',
  PASSWORD_FAILED:"Username or Password mismatch",
  ATTACHEMNT_REMOVE:"Attachment remove successfully ",
  NEW_PROJECT_ADDED:"New Project is Added",
  CREATEION_FAILED: "Creation Failed"
};
